// ============================================================================
// Payload Interior Types
// These are the types inside payload_json — NOT generated by specta.
// IPC boundary types (AnalysisRun, HistoryListItem, etc.) come from $lib/ipc.
// ============================================================================

// ============================================================================
// SEO Report Types (mirroring pagelens_core::seo)
// ============================================================================

export type Severity = 'Error' | 'Warning' | 'Info'

export interface Issue {
  severity: Severity
  message: string
  category: string
}

export interface MetaInfo {
  charset: boolean
  viewport: boolean
  title: string | null
  description: string | null
  language: string | null
  robots: string | null
}

export interface OpenGraphInfo {
  title: string | null
  description: string | null
  og_type: string | null
  url: string | null
  image: string | null
}

export interface TwitterCardInfo {
  card: string | null
  title: string | null
  description: string | null
  image: string | null
}

export interface HeadingsInfo {
  h1_count: number
  h2_count: number
  h3_count: number
  h4_count: number
  h5_count: number
  h6_count: number
  structure: string[]
}

export interface ImageInfo {
  src: string
  alt: string | null
  has_alt: boolean
}

export interface StructuredData {
  schema_type: string
  raw: string
}

export interface SeoReport {
  score: number
  meta: MetaInfo
  open_graph: OpenGraphInfo
  twitter_card: TwitterCardInfo
  canonical_url: string | null
  headings: HeadingsInfo
  images: ImageInfo[]
  structured_data: StructuredData[]
  issues: Issue[]
}

// ============================================================================
// Snapshot Types (mirroring pagelens_core::snapshot)
// ============================================================================

export interface PerformanceTiming {
  navigation_start: number
  dom_interactive: number | null
  dom_content_loaded: number | null
  load_complete: number | null
  response_start: number | null
  first_paint: number | null
  first_contentful_paint: number | null
}

export interface AccessibilityNode {
  role: string
  name: string | null
  level: number | null
  children: AccessibilityNode[]
}

export interface ReferencedAssets {
  javascript: string[]
  stylesheets: string[]
  media: string[]
}

export interface CaptureIssue {
  stage: string
  message: string
}

export interface ComputedStyle {
  selector: string
  color: string | null
  background_color: string | null
  font_size: string | null
  font_weight: string | null
}

export interface Snapshot {
  url: string
  title: string
  html: string
  accessibility_tree: AccessibilityNode[]
  performance_timing: PerformanceTiming
  computed_styles: ComputedStyle[]
  referenced_assets: ReferencedAssets
  capture_issues: CaptureIssue[]
}

// ============================================================================
// Single Page Payload (parsed from payload_json for single-page analysis)
// ============================================================================

export interface SinglePagePayload {
  snapshot: Snapshot
  seo_report: SeoReport
}

// ============================================================================
// Crawl Types (mirroring pagelens_core::crawl)
// ============================================================================

export interface CrawledPage {
  url: string
  snapshot: Snapshot
  seo_report: SeoReport
  depth: number
  links_found: string[]
  success: boolean
  error: string | null
}

export interface CrawlStats {
  total_pages: number
  crawled_pages: number
  failed_pages: number
  external_links: number
  crawl_time_ms: number
  avg_page_load_ms: number
}

export interface AggregateMetrics {
  avg_seo_score: number
  min_seo_score: number
  max_seo_score: number
  total_issues: number
  total_errors: number
  total_warnings: number
  score_distribution: number[]
}

export interface CrawlResult {
  seed_url: string
  pages: CrawledPage[]
  skipped_urls: string[]
  stats: CrawlStats
  aggregate: AggregateMetrics
}

// ============================================================================
// Site Files Types (mirroring pagelens_core::site_files)
// ============================================================================

export interface SiteFileIssue {
  severity: Severity
  category: string
  message: string
}

export interface RobotsReport {
  url: string
  status: number | null
  found: boolean
  sitemap_directives: string[]
  disallow_all_for_star: boolean
}

export type SitemapKind = 'UrlSet' | 'SitemapIndex' | 'Unknown'

export interface SitemapReport {
  url: string
  status: number | null
  found: boolean
  kind: SitemapKind
  urls: string[]
  child_sitemaps: string[]
  parse_error: string | null
}

export interface MiscFileReport {
  path: string
  url: string
  status: number | null
  found: boolean
}

export interface SitemapCrawlDiff {
  in_sitemap_not_in_crawl: string[]
  in_crawl_not_in_sitemap: string[]
}

export interface SiteFilesReport {
  base_url: string
  robots: RobotsReport
  sitemaps: SitemapReport[]
  sitemap_urls: string[]
  misc_files: MiscFileReport[]
  crawl_diff: SitemapCrawlDiff | null
  issues: SiteFileIssue[]
}
