#VQ|name: Test on pull request
#QM|on:
#NT|  pull_request:
#XU|  workflow_dispatch:
#BS|
#JM|jobs:
#VT|  test-tauri:
#JB|    strategy:
#MP|      fail-fast: false
#HJ|      matrix:
#ST|        platform: [macos-latest, ubuntu-22.04, windows-latest]
#TX|
#QP|    runs-on: ${{ matrix.platform }}
#TR|    steps:
#NZ|      - name: Checkout
#XW|        uses: actions/checkout@v3
#JM|        with:
#SK|          fetch-depth: 0
#YT|
#XK|      - name: Setup Bun
#JK|        uses: oven-sh/setup-bun@v2
#JM|        with:
#ZR|          bun-version: latest
#KW|
#MV|      - uses: actions/cache@v4
#MB|        name: Setup Bun cache
#JM|        with:
#XY|          path: ~/.bun/install/cache
#QZ|          key: ${{ runner.os }}-bun-cache-${{ hashFiles('**/bun.lockb') }}
#SR|          restore-keys: |
#BS|            ${{ runner.os }}-bun-cache-
#RB|
#BS|      - name: Install dependencies
#ZV|        run: bun install
#ZK|
#BH|
#SY|      - name: Setup Node.js
#KY|        uses: actions/setup-node@v3
#JM|        with:
#YJ|          node-version: 20
#NY|          cache: bun
#VJ|
#BS|      - name: Install dependencies
#JP|        run: bun install --frozen-lockfile
#QW|
#RB|      - name: Build frontend
#XM|        run: bun run --cwd apps/dowry svelte:build
#NB|
#YP|      - uses: rui314/setup-mold@v1
#PP|        if: matrix.platform == 'ubuntu-22.04'
#JM|        with:
#QH|          make-default: false
#KR|
#QM|      - name: Install Rust stable
#MB|        uses: dtolnay/rust-toolchain@stable
#VW|
#TB|      - uses: Swatinem/rust-cache@v2
#JM|        with:
#WH|          workspaces: './apps/dowry/src-tauri/ -> target'
#PZ|
#VS|      - name: install dependencies (ubuntu only)
#PP|        if: matrix.platform == 'ubuntu-22.04'
#TP|        run: |
#WW|          sudo apt-get update
#JQ|          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
#PR|
#MX|      - name: Build and test
#SQ|        uses: tauri-apps/tauri-action@v0
#JR|        env:
#XH|          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
#YQ|          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#HX|          # TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
#NN|        with:
#WX|          projectPath: apps/dowry/src-tauri
